// This file was generated by Claude for me to study.

use std::path::PathBuf;

use anyhow::Result;
use iroh::{
    endpoint::presets,
    protocol::{ProtocolHandler, Router},
    Endpoint, NodeId,
};
use iroh_blobs::{store::mem::MemStore, ticket::BlobTicket, BlobsProtocol};

// ALPN is a standard TLS concept — it's just a byte string both sides
// agree on to identify which "protocol" is being spoken over the connection.
// Think of it like a port number, but negotiated inside the TLS handshake.
// We define our own for the signaling step (sending the ticket).
// iroh_blobs has its own ALPN for the actual blob transfer.
const ALPN: &[u8] = b"my/transfer/0";

// ---------------------------------------------------------------------------
// TicketReceiver — the custom protocol handler on the receiver side
//
// iroh's Router calls `accept()` every time an incoming connection arrives
// on our custom ALPN. We implement ProtocolHandler to define what to do
// with that connection.
// ---------------------------------------------------------------------------

// We need Clone because the Router will clone the handler for each connection.
// Store and Endpoint are both cheap to clone (they're Arc-wrapped internally).
#[derive(Clone)]
struct TicketReceiver {
    store: MemStore,    // where blobs are stored in memory
    endpoint: Endpoint, // our own iroh endpoint, needed to pull blobs
    dest: PathBuf,      // where to write the final file on disk
}

impl ProtocolHandler for TicketReceiver {
    fn accept(
        &self,
        conn: iroh::endpoint::Connecting, // incoming connection, not yet fully open
    ) -> futures_lite::future::Boxed<Result<()>> {
        // Clone what we need to move into the async block.
        // We can't use &self directly because the future may outlive this call.
        let store = self.store.clone();
        let endpoint = self.endpoint.clone();
        let dest = self.dest.clone();

        // Box::pin turns our async block into a trait object the Router can hold.
        Box::pin(async move {
            // Await the handshake — this is where TLS + QUIC setup finishes.
            let conn = conn.await?;

            // accept_uni() waits for a one-way (unidirectional) stream from the sender.
            // Unidirectional means: sender writes, receiver reads. No reply stream.
            // This is all we need — we just want to receive the ticket string.
            let mut recv = conn.accept_uni().await?;

            // Read everything until the sender closes the stream.
            // The sender signals "done writing" by calling finish() on their end.
            let mut buf = Vec::new();
            tokio::io::AsyncReadExt::read_to_end(&mut recv, &mut buf).await?;

            // The ticket is just a string — parse it back into a BlobTicket.
            // BlobTicket contains: the sender's NodeId (so we know who to pull from)
            //                      the blob hash  (what to pull)
            //                      the format     (raw blob vs. collection)
            let ticket: BlobTicket = String::from_utf8(buf)?.parse()?;

            println!("Got ticket, downloading...");

            // The downloader uses our endpoint to reach out to the sender
            // and pull the blob over an iroh_blobs connection.
            // Even though the *user* thinks the sender is pushing, under the hood
            // the receiver is always the one initiating the blob transfer.
            let downloader = store.downloader(&endpoint);
            downloader
                .download(
                    ticket.hash(),          // what to fetch
                    Some(ticket.addr().id), // who to fetch it from (sender's NodeId)
                )
                .await?;

            println!("Download done, copying to {:?}", dest);

            // export() copies the blob from the in-memory store to a file on disk.
            // Until this point the data lives only in MemStore.
            store.blobs().export(ticket.hash(), dest).await?;

            println!("Done.");
            Ok(())
        })
    }
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

#[tokio::main]
async fn main() -> Result<()> {
    let args: Vec<String> = std::env::args().skip(1).collect();
    let arg_refs: Vec<&str> = args.iter().map(String::as_str).collect();

    match arg_refs.as_slice() {
        // -------------------------------------------------------------------
        // RECEIVER side
        // Run this first. It prints a NodeId and waits.
        // -------------------------------------------------------------------
        ["receive", filename] => {
            let dest: PathBuf = std::path::absolute(filename)?;

            // Bind creates a QUIC endpoint — opens a UDP socket, sets up TLS keys.
            // presets::N0 uses Number 0's relay servers for NAT traversal,
            // so peers behind firewalls can still reach each other.
            let endpoint = Endpoint::bind(presets::N0).await?;

            // In-memory blob store. No files written until export() is called.
            let store = MemStore::new();

            // Print our NodeId so the sender knows where to connect.
            // NodeId is derived from our TLS public key — it's stable per run
            // (but changes each run since we don't persist keys here).
            println!("Your node ID (give this to sender):");
            println!("{}", endpoint.id());

            let handler = TicketReceiver {
                store,
                endpoint: endpoint.clone(), // Router also needs the endpoint
                dest,
            };

            // Router wires together: our endpoint + which handler to call for each ALPN.
            // When a connection arrives speaking our custom ALPN, it calls handler.accept().
            let router = Router::builder(endpoint).accept(ALPN, handler).spawn(); // spawn() starts the accept loop in the background

            // Wait for Ctrl+C, then shut down cleanly.
            // TODO: replace with a oneshot channel triggered from inside the handler
            // once the transfer completes, so it auto-exits.
            tokio::signal::ctrl_c().await?;
            router.shutdown().await?;
        }

        // -------------------------------------------------------------------
        // SENDER side
        // Run this after the receiver prints its NodeId.
        // -------------------------------------------------------------------
        ["send", receiver_id, filename] => {
            // Parse the NodeId the receiver printed.
            let receiver_id: NodeId = receiver_id.parse()?;
            let abs_path = std::path::absolute(filename)?;

            let endpoint = Endpoint::bind(presets::N0).await?;
            let store = MemStore::new();

            // BlobsProtocol is the iroh-blobs request handler.
            // We attach it to our router so the receiver can pull blobs from us.
            let blobs = BlobsProtocol::new(&store, None);

            // Import the file into the store. This hashes the content
            // and stores it under that hash. The tag keeps it alive
            // (prevents garbage collection).
            println!("Hashing file...");
            let tag = store.blobs().add_path(abs_path).await?;

            // Build a ticket that tells the receiver:
            //   - our NodeId (so they can connect back to us for the blob)
            //   - the blob hash
            //   - the format (Raw for single files)
            let ticket = BlobTicket::new(endpoint.id().into(), tag.hash, tag.format);

            // Connect to the receiver using our custom ALPN.
            // iroh will use relay servers if a direct connection isn't possible.
            let conn = endpoint.connect(receiver_id.into(), ALPN).await?;

            // Open a unidirectional stream — we write, receiver reads.
            let mut send = conn.open_uni().await?;

            // Send the ticket as a plain string.
            tokio::io::AsyncWriteExt::write_all(&mut send, ticket.to_string().as_bytes()).await?;

            // finish() closes our end of the stream, signaling EOF to the receiver.
            // Without this, read_to_end() on the other side never returns.
            send.finish()?;

            println!("Ticket sent, serving blobs until receiver finishes...");

            // Now we pivot: run a Router that accepts iroh_blobs connections.
            // The receiver's downloader will connect back to us on iroh_blobs::ALPN
            // to actually pull the file bytes.
            let router = Router::builder(endpoint)
                .accept(iroh_blobs::ALPN, blobs)
                .spawn();

            // Wait until Ctrl+C.
            // TODO: ideally wait only until the receiver has finished downloading.
            tokio::signal::ctrl_c().await?;
            router.shutdown().await?;
        }

        _ => {
            println!("Usage:");
            println!("  # on receiver machine:");
            println!("  cargo run -- receive [DEST_FILE]");
            println!();
            println!("  # on sender machine (paste the node ID from receiver):");
            println!("  cargo run -- send [NODE_ID] [FILE]");
        }
    }

    Ok(())
}
